theme: jekyll-theme-slate
title: Welcome to Patrick's homepage
description: A place cataloguing all the interesting matreial I learned in my pursuit of mastering machine learning, statistics and database management.
